import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Emoji picker widget for chat input
class EmojiPickerWidget extends StatefulWidget {
  final void Function(String emoji) onEmojiSelected;
  final VoidCallback? onBackspace;
  final double height;

  const EmojiPickerWidget({
    super.key,
    required this.onEmojiSelected,
    this.onBackspace,
    this.height = 280,
  });

  @override
  State<EmojiPickerWidget> createState() => _EmojiPickerWidgetState();
}

class _EmojiPickerWidgetState extends State<EmojiPickerWidget>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  List<String> _recentEmojis = ['👍', '❤️', '😂', '😊', '🥰', '😘', '🤔', '👋'];

  @override
  void initState() {
    super.initState();
    // 9 kategori: Son Kullanılan, Yüzler, İnsanlar, Hayvanlar, Yiyecek, Aktivite, Objeler, Semboller, Bayraklar
    _tabController = TabController(length: 9, vsync: this);
    _tabController.addListener(() {
      if (!_tabController.indexIsChanging) {
        setState(() {});
      }
    });
    _loadRecentEmojis();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _loadRecentEmojis() async {
    final prefs = await SharedPreferences.getInstance();
    final saved = prefs.getStringList('recentEmojis');
    if (saved != null && saved.isNotEmpty && mounted) {
      setState(() => _recentEmojis = saved);
    }
  }

  Future<void> _saveRecentEmoji(String emoji) async {
    // Remove if already exists, then add to front
    _recentEmojis.remove(emoji);
    _recentEmojis.insert(0, emoji);
    // Keep max 24 recent emojis
    if (_recentEmojis.length > 24) {
      _recentEmojis = _recentEmojis.sublist(0, 24);
    }
    setState(() {});
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setStringList('recentEmojis', _recentEmojis);
  }

  void _onEmojiTapped(String emoji) {
    _saveRecentEmoji(emoji);
    widget.onEmojiSelected(emoji);
  }

  // Emoji categories - now dynamic for recent
  List<_EmojiCategory> get _categories => [
    _EmojiCategory(
      icon: Icons.access_time,
      label: 'Son Kullanılan',
      emojis: _recentEmojis,
    ),
    _EmojiCategory(
      icon: Icons.emoji_emotions,
      label: 'Yüzler',
      emojis: [
        '😀',
        '😃',
        '😄',
        '😁',
        '😆',
        '😅',
        '🤣',
        '😂',
        '🙂',
        '🙃',
        '😉',
        '😊',
        '😇',
        '🥰',
        '😍',
        '🤩',
        '😘',
        '😗',
        '☺️',
        '😚',
        '😙',
        '🥲',
        '😋',
        '😛',
        '😜',
        '🤪',
        '😝',
        '🤑',
        '🤗',
        '🤭',
        '🤫',
        '🤔',
        '🤐',
        '🤨',
        '😐',
        '😑',
        '😶',
        '😏',
        '😒',
        '🙄',
        '😬',
        '🤥',
        '😌',
        '😔',
        '😪',
        '🤤',
        '😴',
        '😷',
        '🤒',
        '🤕',
        '🤢',
        '🤮',
        '🤧',
        '🥵',
        '🥶',
        '🥴',
        '😵',
        '🤯',
        '🤠',
        '🥳',
        '🥸',
        '😎',
        '🤓',
        '🧐',
        '😕',
        '😟',
        '🙁',
        '☹️',
        '😮',
        '😯',
        '😲',
        '😳',
        '🥺',
        '😦',
        '😧',
        '😨',
        '😰',
        '😥',
        '😢',
        '😭',
        '😱',
        '😖',
        '😣',
        '😞',
        '😓',
        '😩',
        '😫',
        '🥱',
        '😤',
        '😡',
        '😠',
        '🤬',
        '😈',
        '👿',
        '💀',
        '☠️',
      ],
    ),
    _EmojiCategory(
      icon: Icons.emoji_people,
      label: 'İnsanlar',
      emojis: [
        '👋',
        '🤚',
        '🖐️',
        '✋',
        '🖖',
        '👌',
        '🤌',
        '🤏',
        '✌️',
        '🤞',
        '🤟',
        '🤘',
        '🤙',
        '👈',
        '👉',
        '👆',
        '🖕',
        '👇',
        '☝️',
        '👍',
        '👎',
        '✊',
        '👊',
        '🤛',
        '🤜',
        '👏',
        '🙌',
        '👐',
        '🤲',
        '🤝',
        '🙏',
        '✍️',
        '💪',
        '🦵',
        '🦶',
        '👂',
        '🦻',
        '👃',
        '🧠',
        '🫀',
        '👀',
        '👁️',
        '👅',
        '👄',
        '💋',
        '👶',
        '🧒',
        '👦',
        '👧',
        '🧑',
        '👱',
        '👨',
        '🧔',
        '👩',
        '🧓',
        '👴',
        '👵',
        '🙍',
        '🙎',
        '🙅',
        '🙆',
        '💁',
        '🙋',
        '🧏',
      ],
    ),
    _EmojiCategory(
      icon: Icons.emoji_nature,
      label: 'Doğa',
      emojis: [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐸',
        '🐵',
        '🙈',
        '🙉',
        '🙊',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐗',
        '🐴',
        '🦄',
        '🐝',
        '🐛',
        '🦋',
        '🐌',
        '🐞',
        '🐜',
        '🪲',
        '🪳',
        '🦟',
        '🦗',
        '🕷️',
        '🦂',
        '🐢',
        '🐍',
        '🦎',
        '🦖',
        '🦕',
        '🐙',
        '🌸',
        '💮',
        '🏵️',
        '🌹',
        '🥀',
        '🌺',
        '🌻',
        '🌼',
        '🌷',
        '🌱',
        '🪴',
        '🌲',
        '🌳',
        '🌴',
        '🌵',
        '🌾',
      ],
    ),
    _EmojiCategory(
      icon: Icons.emoji_food_beverage,
      label: 'Yemek',
      emojis: [
        '🍎',
        '🍐',
        '🍊',
        '🍋',
        '🍌',
        '🍉',
        '🍇',
        '🍓',
        '🫐',
        '🍈',
        '🍒',
        '🍑',
        '🥭',
        '🍍',
        '🥥',
        '🥝',
        '🍅',
        '🍆',
        '🥑',
        '🥦',
        '🥬',
        '🥒',
        '🌶️',
        '🫑',
        '🌽',
        '🥕',
        '🫒',
        '🧄',
        '🧅',
        '🥔',
        '🍠',
        '🥐',
        '🥯',
        '🍞',
        '🥖',
        '🥨',
        '🧀',
        '🥚',
        '🍳',
        '🧈',
        '🥞',
        '🧇',
        '🥓',
        '🥩',
        '🍗',
        '🍖',
        '🦴',
        '🌭',
        '🍔',
        '🍟',
        '🍕',
        '🫓',
        '🥪',
        '🥙',
        '🧆',
        '🌮',
        '🌯',
        '🫔',
        '🥗',
        '🥘',
        '🫕',
        '🍝',
        '🍜',
        '🍲',
        '☕',
        '🍵',
        '🧃',
        '🥤',
        '🧋',
        '🍶',
        '🍺',
        '🍻',
        '🥂',
        '🍷',
        '🥃',
        '🍸',
        '🍹',
        '🧉',
        '🍾',
        '🧊',
      ],
    ),
    _EmojiCategory(
      icon: Icons.emoji_events,
      label: 'Aktiviteler',
      emojis: [
        '⚽',
        '🏀',
        '🏈',
        '⚾',
        '🥎',
        '🎾',
        '🏐',
        '🏉',
        '🥏',
        '🎱',
        '🪀',
        '🏓',
        '🏸',
        '🏒',
        '🏑',
        '🥍',
        '🏏',
        '🪃',
        '🥅',
        '⛳',
        '🪁',
        '🏹',
        '🎣',
        '🤿',
        '🥊',
        '🥋',
        '🎽',
        '🛹',
        '🛼',
        '🛷',
        '⛸️',
        '🥌',
        '🎿',
        '⛷️',
        '🏂',
        '🪂',
        '🏋️',
        '🤼',
        '🤸',
        '⛹️',
        '🤺',
        '🤾',
        '🏌️',
        '🏇',
        '⛷️',
        '🏊',
        '🚴',
        '🚵',
        '🎪',
        '🎭',
        '🎨',
        '🎬',
        '🎤',
        '🎧',
        '🎼',
        '🎹',
        '🥁',
        '🪘',
        '🎷',
        '🎺',
        '🪗',
        '🎸',
        '🪕',
        '🎻',
      ],
    ),
    _EmojiCategory(
      icon: Icons.emoji_objects,
      label: 'Objeler',
      emojis: [
        '⌚',
        '📱',
        '📲',
        '💻',
        '⌨️',
        '🖥️',
        '🖨️',
        '🖱️',
        '💽',
        '💾',
        '💿',
        '📀',
        '📼',
        '📷',
        '📸',
        '📹',
        '🎥',
        '📽️',
        '🎞️',
        '📞',
        '☎️',
        '📟',
        '📠',
        '📺',
        '📻',
        '🎙️',
        '🎚️',
        '🎛️',
        '🧭',
        '⏱️',
        '⏲️',
        '⏰',
        '🕰️',
        '⌛',
        '⏳',
        '📡',
        '🔋',
        '🔌',
        '💡',
        '🔦',
        '🕯️',
        '🪔',
        '🧯',
        '🛢️',
        '💸',
        '💵',
        '💴',
        '💶',
        '💷',
        '🪙',
        '💰',
        '💳',
        '💎',
        '⚖️',
        '🪜',
        '🧰',
        '🪛',
        '🔧',
        '🔨',
        '⚒️',
        '🛠️',
        '⛏️',
        '🪚',
        '🔩',
      ],
    ),
    _EmojiCategory(
      icon: Icons.emoji_symbols,
      label: 'Semboller',
      emojis: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❣️',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '☮️',
        '✝️',
        '☪️',
        '🕉️',
        '☸️',
        '✡️',
        '🔯',
        '🕎',
        '☯️',
        '☦️',
        '🛐',
        '⛎',
        '♈',
        '♉',
        '♊',
        '♋',
        '♌',
        '♍',
        '♎',
        '♏',
        '♐',
        '♑',
        '♒',
        '♓',
        '🆔',
        '⚛️',
        '🉑',
        '☢️',
        '☣️',
        '📴',
        '📳',
        '🈶',
        '🈚',
        '🈸',
        '🈺',
        '🈷️',
        '✴️',
        '🆚',
        '💮',
        '🉐',
        '㊙️',
        '㊗️',
        '🈴',
        '🈵',
        '🈹',
        '✅',
        '☑️',
        '✔️',
        '❌',
        '❎',
        '➕',
        '➖',
        '➗',
        '➰',
        '➿',
        '〽️',
        '✳️',
        '✴️',
        '❇️',
        '©️',
        '®️',
      ],
    ),
    _EmojiCategory(
      icon: Icons.flag,
      label: 'Bayraklar',
      emojis: [
        '🇹🇷',
        '🇺🇸',
        '🇬🇧',
        '🇩🇪',
        '🇫🇷',
        '🇪🇸',
        '🇮🇹',
        '🇳🇱',
        '🇧🇪',
        '🇦🇹',
        '🇨🇭',
        '🇸🇪',
        '🇳🇴',
        '🇩🇰',
        '🇫🇮',
        '🇵🇱',
        '🇷🇺',
        '🇺🇦',
        '🇬🇷',
        '🇵🇹',
        '🇧🇷',
        '🇦🇷',
        '🇲🇽',
        '🇨🇦',
        '🇦🇺',
        '🇯🇵',
        '🇰🇷',
        '🇨🇳',
        '🇮🇳',
        '🇮🇩',
        '🇸🇦',
        '🇦🇪',
        '🇪🇬',
        '🇿🇦',
        '🇳🇬',
        '🇰🇪',
        '🇲🇦',
        '🇹🇳',
        '🇦🇿',
        '🇬🇪',
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Container(
      height: widget.height,
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1C1C1E) : Colors.white,
        border: Border(
          top: BorderSide(color: isDark ? Colors.white12 : Colors.black12),
        ),
      ),
      child: Column(
        children: [
          // Category tabs
          Container(
            height: 44,
            decoration: BoxDecoration(
              border: Border(
                bottom: BorderSide(
                  color: isDark ? Colors.white12 : Colors.black12,
                ),
              ),
            ),
            child: TabBar(
              controller: _tabController,
              isScrollable: true,
              indicatorSize: TabBarIndicatorSize.label,
              indicatorColor: const Color(0xFF7B3FF2),
              labelColor: const Color(0xFF7B3FF2),
              unselectedLabelColor: isDark ? Colors.white54 : Colors.black54,
              tabAlignment: TabAlignment.start,
              tabs: _categories
                  .map((c) => Tab(icon: Icon(c.icon, size: 22)))
                  .toList(),
            ),
          ),

          // Emoji grid
          Expanded(
            child: TabBarView(
              controller: _tabController,
              children: _categories.map((category) {
                return GridView.builder(
                  padding: const EdgeInsets.all(8),
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 8,
                    childAspectRatio: 1,
                  ),
                  itemCount: category.emojis.length,
                  itemBuilder: (context, index) {
                    final emoji = category.emojis[index];
                    return GestureDetector(
                      onTap: () => _onEmojiTapped(emoji),
                      child: Container(
                        alignment: Alignment.center,
                        child: Text(
                          emoji,
                          style: const TextStyle(fontSize: 26),
                        ),
                      ),
                    );
                  },
                );
              }).toList(),
            ),
          ),

          // Bottom bar with backspace
          Container(
            height: 44,
            padding: const EdgeInsets.symmetric(horizontal: 8),
            decoration: BoxDecoration(
              border: Border(
                top: BorderSide(
                  color: isDark ? Colors.white12 : Colors.black12,
                ),
              ),
            ),
            child: Row(
              children: [
                // Search (placeholder)
                Expanded(
                  child: Container(
                    height: 32,
                    margin: const EdgeInsets.symmetric(vertical: 6),
                    padding: const EdgeInsets.symmetric(horizontal: 12),
                    decoration: BoxDecoration(
                      color: isDark ? Colors.white10 : Colors.grey.shade200,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Row(
                      children: [
                        Icon(
                          Icons.search,
                          size: 18,
                          color: isDark ? Colors.white38 : Colors.black38,
                        ),
                        const SizedBox(width: 8),
                        Text(
                          'Emoji ara',
                          style: TextStyle(
                            color: isDark ? Colors.white38 : Colors.black38,
                            fontSize: 14,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                // Backspace
                GestureDetector(
                  onTap: widget.onBackspace,
                  onLongPress: widget.onBackspace,
                  child: Container(
                    width: 44,
                    height: 32,
                    decoration: BoxDecoration(
                      color: isDark ? Colors.white10 : Colors.grey.shade200,
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Icon(
                      Icons.backspace_outlined,
                      size: 20,
                      color: isDark ? Colors.white54 : Colors.black54,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _EmojiCategory {
  final IconData icon;
  final String label;
  final List<String> emojis;

  const _EmojiCategory({
    required this.icon,
    required this.label,
    required this.emojis,
  });
}
